on:
  workflow_dispatch:

jobs:
  docker:
    name: Build and push Docker image
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        with:
          platforms: arm,arm64

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Compute image metadata
        id: image
        run: |
          TS=$(TZ=Etc/UTC date '+%Y%m%d%H%M%S')
          SHA=$(git rev-parse --short "$GITHUB_SHA")
          TAG="${TS}-${SHA}"
          echo "tag=${TAG}" > "$GITHUB_OUTPUT"

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          push: true
          cache-from: type=gha
          cache-to: type=gha,mode=max
          platforms: linux/arm/v6,linux/arm64,linux/amd64
          tags: |-
            ghcr.io/mkuznets/jeepity:latest
            ghcr.io/mkuznets/jeepity:${{ steps.image.outputs.tag }}
